import React from 'react';
import { FullReportData } from '../types';
import Icon from './Icon';

interface ReportViewProps {
  data: FullReportData;
  onBack: () => void;
}

const ReportView: React.FC<ReportViewProps> = ({ data, onBack }) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="min-h-screen bg-slate-100 py-8 px-4 print:bg-white print:p-0">
      {/* Toolbar - Hidden when printing */}
      <div className="max-w-4xl mx-auto mb-6 flex justify-between items-center print:hidden">
        <button 
          onClick={onBack}
          className="flex items-center gap-2 text-slate-600 hover:text-slate-900 font-medium px-4 py-2 rounded-lg hover:bg-white transition-colors"
        >
          <Icon name="ChevronRight" className="rotate-180" size={20} /> Back to Chat
        </button>
        <button 
          onClick={handlePrint}
          className="flex items-center gap-2 bg-indigo-600 text-white px-6 py-2 rounded-lg font-bold hover:bg-indigo-700 transition-shadow shadow-md"
        >
          <Icon name="Printer" size={20} /> Print / Save PDF
        </button>
      </div>

      {/* Report Sheet */}
      <div className="max-w-4xl mx-auto bg-white shadow-xl rounded-none sm:rounded-sm p-12 print:shadow-none print:w-full print:max-w-none">
        
        {/* Header */}
        <header className="border-b-2 border-slate-900 pb-6 mb-8 flex justify-between items-end">
          <div>
            <h1 className="text-4xl font-extrabold text-slate-900 mb-2">Strategic Analysis Report</h1>
            <p className="text-slate-500 font-medium">Generated by SolveSmart</p>
          </div>
          <div className="text-right">
            <p className="text-sm text-slate-400">Date</p>
            <p className="font-medium text-slate-900">{new Date().toLocaleDateString()}</p>
          </div>
        </header>

        {/* 1. Problem Definition */}
        <section className="mb-10">
          <div className="flex items-center gap-3 mb-4">
            <div className="bg-indigo-600 text-white p-1.5 rounded">
               <Icon name="Target" size={20} />
            </div>
            <h2 className="text-xl font-bold text-slate-900 uppercase tracking-wide">1. Problem Definition</h2>
          </div>
          
          <div className="bg-slate-50 p-6 border-l-4 border-indigo-600 mb-4">
            <h3 className="text-xs font-bold text-indigo-600 uppercase mb-2">Original Statement</h3>
            <p className="text-slate-600 mb-4 italic">"{data.originalProblem}"</p>
            
            <h3 className="text-xs font-bold text-emerald-600 uppercase mb-2">Refined Hypothesis (SMART)</h3>
            <p className="text-xl font-medium text-slate-900">
              {data.smartAnalysis?.improvedStatement || "Analysis Pending"}
            </p>
          </div>
          
          {data.smartAnalysis && (
            <div className="grid grid-cols-2 gap-6 mt-4">
               <div>
                  <h4 className="font-bold text-slate-800 text-sm mb-2">Key Stakeholders</h4>
                  <ul className="list-disc list-inside text-sm text-slate-600">
                    {data.smartAnalysis.potentialStakeholders.map((s, i) => <li key={i}>{s}</li>)}
                  </ul>
               </div>
               <div>
                  <h4 className="font-bold text-slate-800 text-sm mb-2">Identified Biases</h4>
                  <ul className="list-disc list-inside text-sm text-slate-600">
                    {data.smartAnalysis.identifiedBiases.map((b, i) => <li key={i}>{b}</li>)}
                  </ul>
               </div>
            </div>
          )}
        </section>

        {/* 2. Structured Breakdown */}
        {data.issueTree && (
          <section className="mb-10 break-inside-avoid">
            <div className="flex items-center gap-3 mb-4">
              <div className="bg-indigo-600 text-white p-1.5 rounded">
                <Icon name="Layers" size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-900 uppercase tracking-wide">2. Structural Breakdown (MECE)</h2>
            </div>
            
            <div className="border border-slate-200 rounded-lg p-6">
              <div className="flex flex-col items-center">
                 <div className="bg-indigo-600 text-white px-4 py-2 rounded font-bold mb-4">{data.issueTree.root.label}</div>
                 <div className="w-0.5 h-4 bg-slate-300 mb-4"></div>
                 <div className="flex flex-wrap justify-center gap-8">
                    {data.issueTree.root.children?.map((cat, idx) => (
                       <div key={idx} className="flex flex-col items-center">
                          <div className="bg-indigo-50 text-indigo-800 border border-indigo-100 px-3 py-1.5 rounded font-medium text-sm mb-3">
                             {cat.label}
                          </div>
                          {cat.children && (
                             <ul className="space-y-2 text-center">
                                {cat.children.map((issue, cIdx) => (
                                   <li key={cIdx} className="text-xs text-slate-600 bg-white border border-slate-200 px-2 py-1 rounded shadow-sm">
                                      {issue.label}
                                   </li>
                                ))}
                             </ul>
                          )}
                       </div>
                    ))}
                 </div>
              </div>
            </div>
          </section>
        )}

        {/* 3. Prioritization */}
        {data.prioritization && (
          <section className="mb-10 break-inside-avoid">
            <div className="flex items-center gap-3 mb-4">
              <div className="bg-indigo-600 text-white p-1.5 rounded">
                <Icon name="ListOrdered" size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-900 uppercase tracking-wide">3. Priority Issues (80/20)</h2>
            </div>
            
            <div className="bg-slate-50 p-4 rounded-lg mb-4">
               <p className="text-sm text-slate-700 italic">{data.prioritization.paretoSummary}</p>
            </div>

            <div className="grid grid-cols-2 gap-4">
               <div className="border border-emerald-200 bg-emerald-50/50 p-4 rounded">
                  <h4 className="font-bold text-emerald-800 text-sm mb-2 uppercase">Quick Wins</h4>
                  <ul className="text-sm space-y-1">
                     {data.prioritization.items.filter(i => i.quadrant === 'Quick Wins').map((i, idx) => (
                        <li key={idx} className="text-emerald-900">• {i.label}</li>
                     ))}
                  </ul>
               </div>
               <div className="border border-blue-200 bg-blue-50/50 p-4 rounded">
                  <h4 className="font-bold text-blue-800 text-sm mb-2 uppercase">Major Projects</h4>
                  <ul className="text-sm space-y-1">
                     {data.prioritization.items.filter(i => i.quadrant === 'Major Projects').map((i, idx) => (
                        <li key={idx} className="text-blue-900">• {i.label}</li>
                     ))}
                  </ul>
               </div>
            </div>
          </section>
        )}

        {/* 4. Recommendation */}
        {data.synthesis && (
          <section className="break-inside-avoid">
            <div className="flex items-center gap-3 mb-4">
              <div className="bg-indigo-600 text-white p-1.5 rounded">
                <Icon name="FileText" size={20} />
              </div>
              <h2 className="text-xl font-bold text-slate-900 uppercase tracking-wide">4. Strategic Recommendation</h2>
            </div>

            <div className="bg-white border-2 border-slate-900 p-8 shadow-[4px_4px_0px_rgba(15,23,42,1)] mb-8">
               <h3 className="text-lg font-bold text-slate-900 mb-4">{data.synthesis.recommendation.text}</h3>
               
               <div className="grid grid-cols-3 gap-6 mt-6">
                  <div>
                     <h4 className="text-xs font-bold text-slate-400 uppercase mb-2">Action Plan</h4>
                     <ul className="text-sm text-slate-700 space-y-1">
                        {data.synthesis.recommendation.actionableSteps.map((s, i) => <li key={i}>• {s}</li>)}
                     </ul>
                  </div>
                  <div>
                     <h4 className="text-xs font-bold text-slate-400 uppercase mb-2">Stakeholders</h4>
                     <ul className="text-sm text-slate-700 space-y-1">
                        {data.synthesis.recommendation.stakeholders.map((s, i) => <li key={i}>• {s}</li>)}
                     </ul>
                  </div>
                  <div>
                     <h4 className="text-xs font-bold text-slate-400 uppercase mb-2">Resources</h4>
                     <ul className="text-sm text-slate-700 space-y-1">
                        {data.synthesis.recommendation.resources.map((s, i) => <li key={i}>• {s}</li>)}
                     </ul>
                  </div>
               </div>
            </div>

            {/* Synthesis Note */}
            <div className="bg-slate-100 p-6 rounded italic text-slate-600 border-l-4 border-slate-300">
               <span className="font-bold not-italic text-slate-900">Synthesis: </span>
               {data.synthesis.synthesis}
            </div>
          </section>
        )}
      </div>
    </div>
  );
};

export default ReportView;